#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

audit_domain () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  audit_domain "$1" "www"
  audit_domain "$1" "lb-01"
  audit_domain "$1" "web-01"
  audit_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  audit_domain "$1" "$2"
fi
