#!usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

# Function to get and display info about a subdomain
domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | TR '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '(print "The subdomain " $1 " is a " $2 " record and points to " $3")'
}

# Check the number of args passed to script
if [ "$#" == 1 ]
then
    # if only 1 arg, call the domain info func
    # with predefined subdomain names
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    # if there are 2 args, call domain info func
    # with passed args
    domain_info "$1" "$2"
fi
