#!usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

function audit_subdomain {
    local domain="$1"
    local subdomain="$2"
    local record_type=$(dig +short -t "$subdomain" "$domain" | awk '{print toupper($1)}')
    local destination=$(dig +short -t "$subdomain" "$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    audit_subdomain "$domain" "www"
    audit_subdomain "$domain" "lb-01"
    audit_subdomain "$domain" "web-01"
    audit_subdomain "$domain" "web-02"
else
    audit_subdomain "$domain" "$subdomain"
fi
