#!/usr/bin/env bash
# Update server software and install nginx webserver

# Update server software
sudo apt-get --yes update
sudo apt-get --yes install nginx
sudo ufw allow 'Nginx HTTP'

# Create index.html file
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
service nginx restart
