#!/usr/bin/env bash
# Debugging web server, Nginx must be running, and listening on port 80
# of all the server’s active IPv4 IPs
# Bash script that configures a server

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
